### ISSUE TITLE
Pull request template with checklist

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#714]
I'm often overlooking the changelog when adding a new feature, maybe a simple checklist from a pull request template could help to guide through the addition of a feature. For example:

- [ ] followed the style guide (see development guide)
- [ ] add regression tests (see `test/`)
- [ ] add documentation and manual entries (see `doc/`)
- [ ] add new feature to change log (see CHANGELOG.rst)
- [ ] add myself to author list (see AUTHORS.rst)
